/* eslint-disable no-magic-numbers */

const TERRAIN = require('../types/terrain');

module.exports = {
  [TERRAIN.PLAINS]: 1,
  [TERRAIN.HILLS]: 1,
  [TERRAIN.MOUNTAINS]: 2,
  [TERRAIN.CLIFF]: 3,
  [TERRAIN.VEGETATION_RARE]: -1,
  [TERRAIN.VEGETATION_LUSH]: -2,
  [TERRAIN.CHASM]: 0,
  [TERRAIN.CAVE]: 3,
  [TERRAIN.RIVER]: -1,
  [TERRAIN.LAKE]: -1,
  [TERRAIN.LIQUID_SURFACE]: -1,
  [TERRAIN.LIQUID_BELOW]: 1,
  [TERRAIN.SWAMP]: -1,
  [TERRAIN.GLACIER]: 3,
  [TERRAIN.LAVA_LIQUID]: 0,
  [TERRAIN.LAVA_SOLID]: 4,
  [TERRAIN.ALIEN_STRUCTURE]: 0,
  [TERRAIN.ALIEN_CITY]: 2
};
