/* eslint-disable no-magic-numbers */

export default {
  PLAINS: 1,
  HILLS: 2,
  MOUNTAINS: 3,
  CLIFF: 4,
  VEGETATION_RARE: 5,
  VEGETATION_LUSH: 6,
  CHASM: 7,
  CAVE: 8,
  RIVER: 9,
  LAKE: 10,
  LIQUID_SURFACE: 11,
  LIQUID_BELOW: 12,
  SWAMP: 13,
  GLACIER: 14,
  LAVA_LIQUID: 15,
  LAVA_SOLID: 16,
  ALIEN_STRUCTURE: 17,
  ALIEN_CITY: 18
};
